const actionTypes = {
  FETCH_ACCOUNTS: 'FETCH_ACCOUNTS',
  SET_LOADING: 'SET_LOADING',
  MAKE_VISIBLE: 'MAKE_VISIBLE',
  ADD_FETCHED_CAMPAIGNS: 'ADD_FETCHED_CAMPAIGNS',
  FETCH_CAMPAIGN_SUMMARY: 'FETCH_CAMPAIGN_SUMMARY',
  ACCOUNT_INFO_REQUESTED: 'ACCOUNT_INFO_REQUESTED',
};

export { actionTypes };
